<div align='center'><h1>Word Embedding With gensim</h1></div>

Word embedding also reffered to as distributed semantic model or semantic vector space or vector space model is a language modeling and feature learning technique that clusters similar words together. The most commond word embedding vectors are word2vec (Google), Glove (Stanford) and fastest (Facebook). Word embedding is applied in text classification, document clustering,dimensional reduction,topic modeling, feature generation among other NLP tasks such as sentiment analysis.<p>
Unlike the Latent Semantic Analysis technique that ignores words order and context the word embedding technique considers the order of words and context in the sentence.</p>
<p>Word2Vec employs the Continous Bag of Word model (CBOW) and Skip-gram model</p>
<p>gensim is a python library for topic modeling. It's used to analyse text-documents for semantic relationship and other NLP tasks.</p>

Install gensim

In [1]:
# !pip install gensim

Import libraries

In [2]:
import pandas as pd
import numpy as np

from nltk.tokenize import word_tokenize
import gensim


import warnings

In [3]:
warnings.filterwarnings('ignore')

Load data from csv

In [4]:
train=pd.read_csv('datasets/Sentiment Analysis on Movie Reviews/train.tsv',sep='\t')
test=pd.read_csv('datasets/Sentiment Analysis on Movie Reviews/test.tsv',sep='\t')

Given a tokenized text below

In [5]:
sentence = [['first', 'sentence'], ['second', 'sentence'],['The','quick','brown','fox','jumped','over','the','lazy','dog']]

In [6]:
sentence

[['first', 'sentence'],
 ['second', 'sentence'],
 ['The', 'quick', 'brown', 'fox', 'jumped', 'over', 'the', 'lazy', 'dog']]

Creating our word2vec model

In [7]:
model=gensim.models.Word2Vec(sentence, min_count=1)
model

Retrieve trained tokens

In [8]:
print(model.wv.vocab)

{'first': <gensim.models.keyedvectors.Vocab object at 0x00000214982FF668>, 'sentence': <gensim.models.keyedvectors.Vocab object at 0x00000214982FF6A0>, 'second': <gensim.models.keyedvectors.Vocab object at 0x00000214982FF6D8>, 'The': <gensim.models.keyedvectors.Vocab object at 0x00000214982FF710>, 'quick': <gensim.models.keyedvectors.Vocab object at 0x00000214982FF7F0>, 'brown': <gensim.models.keyedvectors.Vocab object at 0x00000214982FF908>, 'fox': <gensim.models.keyedvectors.Vocab object at 0x00000214982FFA20>, 'jumped': <gensim.models.keyedvectors.Vocab object at 0x00000214982FF7B8>, 'over': <gensim.models.keyedvectors.Vocab object at 0x00000214982FFD30>, 'the': <gensim.models.keyedvectors.Vocab object at 0x00000214982FFE10>, 'lazy': <gensim.models.keyedvectors.Vocab object at 0x00000214982FFE80>, 'dog': <gensim.models.keyedvectors.Vocab object at 0x00000214982FFEB8>}


Retrieve specific token

In [9]:
model['brown']

array([-4.2133033e-03, -4.1468404e-03,  3.5501192e-03,  1.9773499e-03,
       -3.8439210e-03, -2.3370753e-03, -2.5862933e-03,  4.7785128e-03,
       -2.3628618e-03, -3.9900574e-03, -4.3501174e-03,  4.3709385e-03,
        1.5694880e-03,  4.9045408e-04, -4.8499834e-03,  4.4760057e-03,
        3.4979009e-03,  1.5725266e-03, -2.4954190e-03,  2.1538648e-03,
       -7.4231252e-04, -4.8448308e-03, -2.1602346e-03,  1.0299633e-03,
        1.9122426e-03, -2.1443358e-03, -8.6653850e-04, -6.2897825e-04,
       -6.6145009e-04, -7.5320924e-07, -2.9841023e-03, -3.9988770e-03,
        1.1172598e-03, -3.9438014e-03,  1.2881323e-03, -1.5997713e-03,
        2.4644195e-03,  3.9324677e-03,  1.9670150e-04,  8.6464963e-05,
       -3.0795226e-03,  2.9440979e-03, -4.5456258e-03,  4.0142573e-03,
        1.1610993e-03, -2.7284995e-03, -3.7780118e-03,  3.3455668e-03,
        4.1449093e-03, -2.6031544e-03,  6.0553110e-04, -9.6098846e-04,
        3.3479708e-03, -4.9109398e-03, -3.7751268e-03, -1.4853446e-03,
      

In [10]:
model['fox']

array([-1.4020096e-03, -4.2423438e-03,  3.7243478e-03, -3.7726329e-03,
        4.0324302e-03,  3.0911160e-03,  7.0586108e-04, -1.1325873e-03,
        4.8682434e-03,  1.7595576e-03, -1.5104869e-03, -1.4333397e-03,
        1.6859388e-03, -2.8028684e-03,  1.4997101e-03, -1.7186148e-04,
       -1.2604368e-03,  1.0603896e-03, -1.1595790e-03, -4.8192181e-03,
       -1.7920536e-03, -2.7532284e-03, -3.1439932e-03, -3.9328909e-03,
       -5.1050307e-04,  3.9696470e-03,  3.1739920e-03, -1.5088958e-03,
       -3.1638080e-03, -2.3056897e-03,  3.6154471e-03, -4.1556987e-03,
        4.2755823e-04, -8.8977389e-04, -3.5432708e-03, -4.7446574e-05,
        3.9908825e-04,  3.7676224e-03, -3.3464681e-03,  2.8239053e-03,
       -4.9581355e-03,  4.6536541e-03,  9.1226968e-05, -2.4793202e-03,
        3.8798878e-03,  4.5912960e-03,  1.2949150e-03, -9.9112069e-05,
       -2.0052127e-03, -3.4109557e-03, -4.1654422e-03,  1.0489922e-03,
       -3.2214606e-03, -2.7957771e-03,  1.7985987e-03, -2.7461911e-03,
      

<h5>Out of Vocabulary word problem (OOV)<h5 />

This is a major weakness of the word embedding where words that are not represented in the training corpus are not mapped to any vector space.

If we use the word 'India' which is not in the training corpus we get an error since the model doesn't recognize it.

In [11]:
model['India']

KeyError: "word 'India' not in vocabulary"

The Out of Vocabulary word problem is also case sensitive i.e the word fox and Fox are two different words.

In [12]:
model['fox']

array([-1.4020096e-03, -4.2423438e-03,  3.7243478e-03, -3.7726329e-03,
        4.0324302e-03,  3.0911160e-03,  7.0586108e-04, -1.1325873e-03,
        4.8682434e-03,  1.7595576e-03, -1.5104869e-03, -1.4333397e-03,
        1.6859388e-03, -2.8028684e-03,  1.4997101e-03, -1.7186148e-04,
       -1.2604368e-03,  1.0603896e-03, -1.1595790e-03, -4.8192181e-03,
       -1.7920536e-03, -2.7532284e-03, -3.1439932e-03, -3.9328909e-03,
       -5.1050307e-04,  3.9696470e-03,  3.1739920e-03, -1.5088958e-03,
       -3.1638080e-03, -2.3056897e-03,  3.6154471e-03, -4.1556987e-03,
        4.2755823e-04, -8.8977389e-04, -3.5432708e-03, -4.7446574e-05,
        3.9908825e-04,  3.7676224e-03, -3.3464681e-03,  2.8239053e-03,
       -4.9581355e-03,  4.6536541e-03,  9.1226968e-05, -2.4793202e-03,
        3.8798878e-03,  4.5912960e-03,  1.2949150e-03, -9.9112069e-05,
       -2.0052127e-03, -3.4109557e-03, -4.1654422e-03,  1.0489922e-03,
       -3.2214606e-03, -2.7957771e-03,  1.7985987e-03, -2.7461911e-03,
      

In [13]:
model['Fox']

KeyError: "word 'Fox' not in vocabulary"

In [49]:
def document_vecors(text):
    doc_vectors=[word for word in list(text) if word in model.wv.vocab]
    return np.mean(model[doc_vectors], axis=0)

In [15]:
document_vecors(['brown','fox'])

array([-2.8076565e-03, -4.1945921e-03,  3.6372335e-03, -8.9764153e-04,
        9.4254618e-05,  3.7702033e-04, -9.4021612e-04,  1.8229627e-03,
        1.2526908e-03, -1.1152499e-03, -2.9303022e-03,  1.4687994e-03,
        1.6277134e-03, -1.1562072e-03, -1.6751366e-03,  2.1520720e-03,
        1.1187320e-03,  1.3164581e-03, -1.8274990e-03, -1.3326766e-03,
       -1.2671831e-03, -3.7990296e-03, -2.6521138e-03, -1.4514639e-03,
        7.0086977e-04,  9.1265561e-04,  1.1537268e-03, -1.0689370e-03,
       -1.9126290e-03, -1.1532215e-03,  3.1567237e-04, -4.0772879e-03,
        7.7240902e-04, -2.4167877e-03, -1.1275692e-03, -8.2360895e-04,
        1.4317539e-03,  3.8500451e-03, -1.5748832e-03,  1.4551851e-03,
       -4.0188292e-03,  3.7988760e-03, -2.2271995e-03,  7.6746859e-04,
        2.5204935e-03,  9.3139824e-04, -1.2415485e-03,  1.6232274e-03,
        1.0698483e-03, -3.0070550e-03, -1.7799556e-03,  4.4001848e-05,
        6.3255080e-05, -3.8533583e-03, -9.8826410e-04, -2.1157679e-03,
      

<h5>Creating embedding from dataframe data<h5>

In [16]:
train.head()

PhraseId  SentenceId                                             Phrase  \
0         1           1  A series of escapades demonstrating the adage ...   
1         2           1  A series of escapades demonstrating the adage ...   
2         3           1                                           A series   
3         4           1                                                  A   
4         5           1                                             series   

   Sentiment  
0          1  
1          2  
2          2  
3          2  
4          2

Tokenize the sentences to words

In [17]:
train['token']=train['Phrase'].apply(lambda x: word_tokenize(x))

Create Word2Vec model

In [18]:
sentiment_w2v=gensim.models.Word2Vec(train['token'], size=500, window=10, min_count=1, iter=20)

Vector size/embedding dimension

In [19]:
sentiment_w2v.vector_size

500

Total number of words in the embedding

In [20]:
len(sentiment_w2v.wv.vocab)

18238

View vocabulary

In [21]:
# print(list(sentiment_w2v.wv.vocab))

Get similar words

In [22]:
sentiment_w2v.most_similar(['rain'],topn=10)

[('coat', 0.6962974071502686),
 ('sweaty', 0.6266077756881714),
 ('shopping', 0.5884391069412231),
 ('desert', 0.5387845635414124),
 ('Tyson', 0.5385549068450928),
 ('lameness', 0.5368521213531494),
 ('Characterisation', 0.5314506888389587),
 ('benchmark', 0.511361837387085),
 ('pastel', 0.5001469254493713),
 ('porn', 0.4979749321937561)]

Get words similar to 'rain' or 'run'

In [23]:
sentiment_w2v.wv.most_similar(positive=['rain','run'],topn=10)

[('coat', 0.5020240545272827),
 ('shopping', 0.4916538894176483),
 ('broke', 0.4786890149116516),
 ('tunnels', 0.4614473581314087),
 ('anonymous', 0.45422470569610596),
 ('stand-up-comedy', 0.45180177688598633),
 ('desert', 0.44589999318122864),
 ('hack-and-slash', 0.44477319717407227),
 ('horses', 0.44421201944351196),
 ('substitutes', 0.4389292001724243)]

Get disimilar words

In [24]:
sentiment_w2v.wv.doesnt_match(['raining','bad','morning'])

'morning'

Get similarity measure between two words

In [25]:
sentiment_w2v.similarity('rain','sun')

0.15875462

Load google word2vec pre-trained embedding

In [26]:
# import gensim.downloader as api
# wv_embedding = api.load('word2vec-google-news-300')

<div align='center'><h1>Conclusion</h1><div />

Word Embedding is a powerful technique of representing text in vector form. This technique ensures that the syntactic and semantic aspect of the text is preserved. By preserving the context of each word in the text we get to infere correctly to the meaning of each word in the discourse of communication. We have looked at Word2Vec which is one of the implementation of Word Embedding. Other Word embedding implementations include glove, and fasttext.<br /><br />
One of the challenges of word embedding is the out of vocabulary word problem. The word that was not in the training corpus for embedding cannot be mapped into any vector space. This is a major challenges since the human language keeps evoling and new vocabularies are being invented daily not to mention errors the exisiting vocabularies by users.